[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[constraint]]
  branch = "release-1.7"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.7"
  name = "k8s.io/apiextensions-apiserver"
