[[constraint]]
  name = "k8s.io/client-go"
  version = "v5.0.1"

[[constraint]]
  version = "kubernetes-1.8.1"
  name = "k8s.io/apimachinery"

[[constraint]]
  version = "kubernetes-1.8.1"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  name = "k8s.io/api"
  revision = "fe29995db37613b9c5b2a647544cf627bfa8d299"
